### ISSUE TITLE
Can you move this project to an organization?

### ISSUE THREAD

**Issue by AndrewMast** [PandawanFr/mcs#1]
Hello! I think you have done a very good job on this so far! I am interested in this project and I want to help.

I was wondering if you could put this in an organization (maybe the org can be named MinecraftScript?) so the community can help. (I know we can fork it and do pull requests, but it is easier in an organization especially if we want to create mini repositories for MCS to link to)

(If you don't know how to move it to an organization, you go to the repo settings -> transfer ownership -> and select the organization)

**Comment by Pandawan** [comment]
Hey, thanks!

I might create an organization, but I won't open it for anyone to edit/modify, simply because I don't want people removing or doing something which I (or people that know what they're doing) can't check. Which is why I decided to make everything with pull requests. 

Therefore, I do not see much use to creating an organization, but I might still do it. 

PS: I am not familiar with organizations since I have never created one before so if there's something I'm missing, please enlighten me.

**Comment by AndrewMast** [comment]
In organizations, you can have members with different permissions. Like you and another person (for example) could edit/modify but people like me could only read/pull request.
